# Change these first
owner: alexandervantrijffel # Your GitHub username
repo: upptimemonitoring # Your Github repository name

# Add your sites here
sites:
  - name: Structura
    url: https://structura.ws
  - name: Last Noted Web
    url: https://lastnoted.com
  - name: Last Noted Eventreporter
    url: https://lastnoted.com/eventreporter
  - name: Last Noted Eventsink
    url: https://lastnoted.com/eventsink
  - name: Smith and Doe Web
    url: https://www.smithanddoe.com
  - name: Smith and Doe Privacy API
    url: https://www.smithanddoe.com/privacy/API/QuickScanModel
  - name: Craftify
    url: https://craftify.nl   
  - name: ProSim Home
    url: https://prosim-ar.com
  - name: ProSim Forum
    url: https://forum.prosim-ar.com
  - name: ProSim Shop
    url: https://shop.prosim-ar.com
  - name: ProSim Downloads
    url: http://cdndl.prosim-ar.com/ProSimB738/
  - name: ProSim lic API#1
    url: $SECRETURL_PROSIM_LICAPI1

assignees: # Users to assign downtime issues (optional)
  - alexandervantrijffel

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: structura.ws
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptimemonitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Upptime monitoring"
  introMessage:
  navbar:
    - title: Status
      href: /upptimemonitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
