# Change these first
owner: alexandervantrijffel # Your GitHub username
repo: upptimemonitoring # Your Github repository name

# Add your sites here
sites:
  - name: Structura
    url: https://structura.ws
    expectedStatusCodes:
      - 200
  - name: Last Noted Web
    url: https://lastnoted.com
    expectedStatusCodes:
      - 200
  - name: Last Noted Eventreporter
    url: https://lastnoted.com/eventreporter
    expectedStatusCodes:
      - 200
  - name: Last Noted Eventsink
    url: https://lastnoted.com/eventsink
    expectedStatusCodes:
      - 200
  - name: Smith and Doe Web
    url: https://www.smithanddoe.com
    expectedStatusCodes:
      - 200
  - name: Smith and Doe Privacy API
    url: https://www.smithanddoe.com/privacy/API/QuickScanModel
    expectedStatusCodes:
      - 200
  - name: Craftify
    url: https://craftify.nl
    expectedStatusCodes:
      - 200
  - name: ProSim Home
    url: https://prosim-ar.com
    expectedStatusCodes:
      - 200
  - name: ProSim Forum
    url: https://forum.prosim-ar.com
    expectedStatusCodes:
      - 200
  - name: ProSim Shop
    url: https://shop.prosim-ar.com
    expectedStatusCodes:
      - 200
  - name: ProSim Downloads
    url: https://cdndl.prosim-ar.com/ProSimB738
    expectedStatusCodes:
      - 200
  - name: ProSim lic API#1
    url: $SECRETURL_PROSIM_LICAPI1
    expectedStatusCodes:
      - 200
  - name: Deloitte Process X-Ray
    url: https://processxray.deloitte.com/x/process-x-ray
    expectedStatusCodes:
      - 200
  - name: TOP Onions
    url: https://www.toponions.com
    expectedStatusCodes:
      - 200
  - name: TOP Taste
    url: https://www.top-taste.com
    expectedStatusCodes:
      - 200
  - name: Lion Foods
    url: https://lionfoods.nl
    expectedStatusCodes:
      - 200
      
user-agent: alexandervantrijffel # fit git api requests

assignees: # Users to assign downtime issues (optional)
  - alexandervantrijffel

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: structura.ws
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptimemonitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Upptime monitoring"
  introMessage:
  navbar:
    - title: Status
      href: https://structura.ws/upptimemonitoring
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
